Repository fulpstation/fulpstation, pull requests merged in 2021-06, with the labels that each got.

#196 Fixes this part of maint being in space in Helios
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix, Modular

#193 Adds workflows to the readme
  fulp_modules/readme.md
Labels: Modular

#198 SeleneStation: Adding air alarm to HFR
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#201 Fixes the atmos engine APC
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#194 Changes how Torpor is dealt with
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#205 Deletes L
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
Labels: Grammar/Spelling, Modular

#203 Fixes the stupid pipes on Heliostation
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix, Map Edit, Modular

#206 Monster hunters spawn, get buffed Fortitude, and no longer take blood to track monsters
  fulp_modules/main_features/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm
Labels: Fix, Modular

#208 SeleneStation: Double grilles in abandoned bar
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular

#209 SeleneStation: Mismatched walls in engineering
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular

#207 fixes brig doc's PDA
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm
Labels: Fix, Modular

#213 SeleneStation: Changed the filing cabinet
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#212 Pico Plush but it actually works this time
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/Z_edits/container_init/machine_init.dm
  fulp_modules/features/toys/code/toys.dm
  fulp_modules/features/toys/icons/toys.dmi
  fulp_modules/features/toys/sound/pico.ogg
Labels: Feature, Map Edit, Modular

#210 SeleneStation: Small botany renovation
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#215 [Selene] Edits (buffs) Chef's CQC
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/selenestation.json
Labels: Fix, Map Edit, Modular

#218 Beefmen can no longer teleport to NOTELEPORT areas
  fulp_modules/main_features/beefmen/code/modules/mob/beefman_trauma.dm
Labels: Fix, Modular

#219 Makes vassal rack/candelabrum use right-click
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
Labels: Modular, Quality of Life

#221 Fixes Tremere revival & cancelling timers
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
Labels: Fix, Modular

#223 Bloodsucker and Monster Hunter antag tips
  fulp_modules/features/antag_tips/code/asset_cache.dm
  fulp_modules/features/antag_tips/html/bloodsucker.html
  fulp_modules/features/antag_tips/html/monsterhunter.html
  fulp_modules/features/antag_tips/html/vassal.html
  fulp_modules/features/antag_tips/icons/bloodsucker.png
  fulp_modules/features/antag_tips/icons/coffin.png
  fulp_modules/features/antag_tips/icons/day.png
  fulp_modules/features/antag_tips/icons/masquerade.png
  fulp_modules/features/antag_tips/icons/monsterhunter.png
  fulp_modules/features/antag_tips/icons/vassal.png
  fulp_modules/features/antag_tips/icons/vassalrack.png
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
Labels: Modular, Quality of Life

#217 Body cameras 2.0
  fulp_modules/Z_edits/container_init/machine_init.dm
  fulp_modules/features/body_cameras/body_camera.dm
  fulp_modules/features/body_cameras/readme.md
  tgstation.dme
Labels: Feature, Modular

#222 Contributors
  config/contributors.txt
  fulp_modules/fulp_configs/code/fulp_world.dm
  fulp_modules/main_features/mentorhelp/mentor.dm
  fulp_modules/main_features/mentorhelp/mentorsay.dm
  fulp_modules/main_features/mentorhelp/mentorwho.dm
Labels: Config, Feature, Modular

#226 Adds Cult Stun Nerf to Antagonist Tips
  fulp_modules/features/antag_tips/html/cultist.html
Labels: Modular, Quality of Life

#229 fulp_config hardcoding
  fulp_modules/fulp_configs/code/fulp_config.dm
Labels: Fix, Modular

#230 [Non-Modular] Beefmen Preferences Fix
  code/modules/client/preferences_savefile.dm
Labels: Fix

#236 changes contributor's msay color
  fulp_modules/main_features/mentorhelp/mentorsay.dm
Labels: Modular, Quality of Life

#234 [Please TM first] Fixes Admins not seeing Msay when deadminned
  fulp_modules/main_features/mentorhelp/mentor.dm
  fulp_modules/main_features/mentorhelp/mentor_clientprocs.dm
  fulp_modules/main_features/mentorhelp/mentorwho.dm
Labels: Fix, Modular

#233 Fixes body camera unregister runtime
  fulp_modules/features/body_cameras/body_camera.dm
Labels: Fix, Modular

#235 fucks with selene a bit idk
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#227 Bloodsuckers - Update 4: Balances & Clan Expansions
  code/___fulp_defines/fulp_defines.dm
  code/game/gamemodes/objective.dm
  code/modules/mob/living/carbon/human/examine.dm
  fulp_modules/features/antag_tips/html/vassal.html
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/vampiric.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/haste.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/bloodsuckers/code/powers/veil.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/monsterhunter_event.dm
  fulp_modules/main_features/bloodsuckers/icons/bloodsucker_icons.dmi
  fulp_modules/main_features/bloodsuckers/readme.MD
  fulp_modules/malkavian_revelations.json
  html/changelogs/AutoChangeLog-pr-59403.yml
  html/changelogs/AutoChangeLog-pr-59463.yml
  html/changelogs/AutoChangeLog-pr-59466.yml
  html/changelogs/AutoChangeLog-pr-59468.yml
  html/changelogs/AutoChangeLog-pr-59469.yml
  tgstation.dme
Labels: Feature, Quality of Life

#237 Removing Bloodsucker's sleeps
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/bloodsuckers/code/powers/veil.dm
  fulp_modules/malkavian_revelations.json
Labels: Code Improvement, Modular

#239 Adds placeholder sprite for distress
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/icons/actions_bloodsucker.dmi
Labels: Modular, Sprites

#240 Adds list of all TG edits our repo causes
  fulp_modules/Z_edits/readme.MD
  fulp_modules/Z_edits/tg_edits.md
  fulp_modules/features/fulp_clothing/digitigrade/readme.md
  fulp_modules/features/fulp_clothing/security/readme.md
Labels: Code Improvement, Modular

#243 Extra pride wings!
  fulp_modules/features/moth_customization/code/moth_antennae.dm
  fulp_modules/features/moth_customization/code/moth_wings.dm
  fulp_modules/features/moth_customization/icons/fulp_moth_antennae.dmi
  fulp_modules/features/moth_customization/icons/fulp_moth_wings.dmi
Labels: Modular, Sprites

#244 Masquerade status effect
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
Labels: Modular, Quality of Life

#242 SeleneStation: Moved camera in SM chamber so users can interact with the air alarm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#190 Re-adds audible screams (now in modular form!)
  fulp_modules/Z_edits/emote/fulp_emote_edits.dm
  tgstation.dme
Labels: Feature, Modular

#245 [Heliostation] Fixes atmos from being sabotaged roundstart
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix, Map Edit, Modular

#246 Fixes admins giving Bloodsucker objectives & Adds monster hunters to admin list
  code/game/gamemodes/objective.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
Labels: Fix

#247 [Selene & Helio] Makes CO2 get filtered back into waste
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular

#248 [Selene] Adds boxing gloves locker
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular, Quality of Life

#250 Removes game breaking oversight.
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular
