Repository fulpstation/fulpstation, pull requests merged in 2021-12, with the labels that each got.

#417 Beefman clothing fixes with a bonus Geneless nerf.
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/features/species/beefmen/beefman_clothing.dm
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/features/species/icons/mob/clothing/beefclothing_worn.dmi
Labels: Balance, Modular

#418 Fulp codebase maintaining: Removes race bans and improves upstream bot
  fulp_modules/Z_edits/species_bans.dm
  fulp_modules/Z_edits/upstream_bot.dm
  fulp_modules/global_vars.dm
  tgstation.dme
Labels: Removal, Modular, Code Improvement

#420 Fix broken pipe at Helio station uno.
  fulp_modules/features/jobs/deputy/deputy.dm
Labels: Balance, Modular

#421 please stop breaking my antag
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#424 [Selene & Helio] Small map fixes
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#423 Brig Physician now requires medical playtime
  fulp_modules/features/jobs/brigdoc/brigdoc.dm
Labels: Balance, Modular

#425 Syriniver shot for Helios and Selene (Removing mentions of toxins)
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#426 Fixed outdated radiation flavortext
  fulp_modules/features/jobs/brigdoc/beacon.dm
Labels: Fix, Modular

#427 Increases the spin and flip cooldowns
  fulp_modules/Z_edits/emote_edits/cooldowns.dm
  tgstation.dme
Labels: Quality of Life, Modular

#415 Misdirection can no longer break the laws of physics
  fulp_modules/features/lisa/joelgun.dm
Labels: Fix, Modular

#428 Deputy update
  fulp_modules/features/jobs/deputy/deputy.dm
  fulp_modules/features/jobs/deputy/deputy_clothing.dm
Labels: Balance, Modular

#429 Changeling Blood Spider nerf
  fulp_modules/Z_edits/antag_edits/changeling_spiders.dm
  fulp_modules/Z_edits/antag_edits/cult_stun.dm
  tgstation.dme
Labels: Merge Conflict, Balance, Modular

#430 Fixes bfeeman locket error sprite
  fulp_modules/features/clothing/neck/beefman_locket.dm
  fulp_modules/features/clothing/neck/beefman_locket.dmi
  fulp_modules/features/clothing/neck/beefman_locket_worn.dmi
  tgstation.dme
Labels: Fix, Modular

#438 Re-adds fulp bans
  fulp_modules/Z_edits/fulp_bans.dm
  tgstation.dme
Labels: Fix, Modular

#437 Puts digitigrade shoes in Garment Bags
  fulp_modules/Z_edits/inititalize_edits/closet_init.dm
  fulp_modules/features/clothing/digitigrade/code/digi_shoes.dm
Labels: Quality of Life, Modular

#439 fulp areas file
  fulp_modules/mapping/helpers/areas.dm
  fulp_modules/mapping/helpers/commission_plaques.dm
  fulp_modules/mapping/helpers/fulp_logo/fulp_logo.dm
  fulp_modules/mapping/helpers/fulp_logo/fulp_logo.dmi
  fulp_modules/mapping/objects/fulp_logo/fulp_logo.dm
  tgstation.dme
Labels: Modular, Code Improvement

#440 Fixes broken ass area on Helios tation
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#431 Bloodsucker code improvements
  code/___fulp_defines/bloodsucker_defines.dm
  fulp_modules/Z_edits/heart.dm
  fulp_modules/features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_guardian.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/brujah.dm
  fulp_modules/features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/features/bloodsuckers/code/powers/distress.dm
  fulp_modules/features/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/_powers_targeted.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/brawn.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/haste.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/bloodsuckers/code/powers/veil.dm
  fulp_modules/features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  tgstation.dme
Labels: Modular, Code Improvement

#443 Hotfix: saves Christmas
  fulp_modules/features/mobs/fulp_mobs.dm
  tgstation.dme
Labels: Fix, Modular

#436 Deputy Code Improvements
  fulp_modules/features/jobs/brigdoc/brigdoc_clothing.dm
  fulp_modules/features/jobs/deputy/_deputy.dm
  fulp_modules/features/jobs/deputy/deputy_gear.dm
  fulp_modules/features/jobs/deputy/deputy_skillchip.dm
  tgstation.dme
Labels: Stale, Modular, Code Improvement

#442 L
  fulp_modules/tg_edits.md
Labels: Modular, Grammar/Spelling

#444 Makes devil mobs code more organized
  fulp_modules/features/mobs/devil.dm
  tgstation.dme
Labels: Modular, Code Improvement

#447 deletes commented out devils file
  fulp_modules/features/mobs/fulp_mobs.dm
Labels: Removal, Modular
