Repository fulpstation/fulpstation, pull requests merged in 2021-07, with the labels that each got.

#254 Removes Brig Physician's security locker/records access.
  fulp_modules/Z_edits/emote/fulp_emote_edits.dm
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc_clothing.dm
  fulp_modules/main_features/jobs/brigdoc/code/landmark.dm
Labels: Balance, Modular

#252 SeleneStation: Atmospheric room pump shift
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular, Quality of Life

#259 Re-adds removed undocumented TG edit and documents it
  fulp_modules/Z_edits/tg_edits.md
  tools/build/build.js
Labels: Code Improvement, Fix

#255 Heliostation's new permabrig
  _maps/heliostation.json
  _maps/map_files/Heliostation/Heliostation.dmm
  fulp_modules/Z_edits/container_init/machine_init.dm
  fulp_modules/Z_edits/malfunction_bot/upstream_bot.dm
  fulp_modules/features/food/code/food.dm
  fulp_modules/features/halloween_event/costumes_2020/onesies.dm
  fulp_modules/features/prison_kitchen/_restaurant.dm
  fulp_modules/features/prison_kitchen/food_overwrites.dm
  fulp_modules/features/prison_kitchen/hos_prefix.txt
  fulp_modules/features/prison_kitchen/icons/bots.dmi
  fulp_modules/features/prison_kitchen/prison_bots.dm
  fulp_modules/features/prison_kitchen/prisoner_prefix.txt
  fulp_modules/features/prison_kitchen/warden_prefix.txt
  fulp_modules/features/toys/code/toys.dm
  fulp_modules/features/toys/icons/toys.dmi
  tgstation.dme
Labels: Map Edit, Modular

#258 Vampire Sunlight Indicator Icon Resprite
  fulp_modules/Z_edits/emote/fulp_emote_edits.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/icons/actions_bloodsucker.dmi
Labels: Modular, Sprites

#249 Bloodsucker Expansion 5: Clan objectives
  code/game/gamemodes/objective.dm
  fulp_modules/Z_edits/emote/fulp_emote_edits.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_recipes.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/main_features/bloodsuckers/icons/vamp_obj.dmi
  fulp_modules/main_features/bloodsuckers/icons/vamp_obj_64.dmi
Labels: Feature, Merge Conflict

#261 Replaces floor with plating
  _maps/map_files/Heliostation/Heliostation.dmm
  fulp_modules/features/prison_kitchen/_restaurant.dm
Labels: Fix, Map Edit, Modular

#262 Crimson Chalice Barsign
  fulp_modules/features/barsigns/barsigns.dm
  fulp_modules/features/barsigns/barsigns.dmi
Labels: Feature, Modular, Sprites

#264 Muting someone from adminhelps now mute you from mentorhelps
  fulp_modules/main_features/mentorhelp/mentorhelp.dm
Labels: Feature, Modular

#265 Fixes lunge permanently slowing you down / Fixes lunge permanently immobilizing you
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
Labels: Fix, Modular

#263 Removes copypaste code from barsigns
  fulp_modules/features/barsigns/barsigns.dm
Labels: Code Improvement, Modular

#267 [Selene] Fixes atmos
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular

#269 Fixes body cameras, buffs Sashes
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/features/body_cameras/body_camera.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman_clothing.dm
  fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm
Labels: Balance, Fix, Modular

#266 Adds PubbyStation
  _maps/_basemap.dm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/pubbystation.json
  config/maps.txt
Labels: Feature, Map Edit

#273 Aspen Moth Wings
  fulp_modules/features/moth_customization/code/moth_antennae.dm
  fulp_modules/features/moth_customization/code/moth_wings.dm
  fulp_modules/features/moth_customization/icons/fulp_moth_antennae.dmi
  fulp_modules/features/moth_customization/icons/fulp_moth_wings.dmi
Labels: Modular, Sprites

#270 nerfs helio's perma
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Balance, Map Edit

#274 Literally just adds felinid bans
  code/___fulp_defines/fulp_defines.dm
  code/modules/admin/sql_ban_system.dm
  fulp_modules/Z_edits/emote_edits/kiss.dm
  fulp_modules/Z_edits/emote_edits/scream.dm
  fulp_modules/Z_edits/race_bans/races.dm
  tgstation.dme
Labels: Quality of Life

#275 Fixes #272
  fulp_modules/main_features/beefmen/code/modules/mob/beefman_clothing.dm
  fulp_modules/main_features/beefmen/icons/mob/clothing/beefclothing.dmi
  fulp_modules/main_features/beefmen/icons/mob/clothing/beefclothing_worn.dmi
Labels: Fix, Modular, Sprites

#277 Fixes aux base on all fulp maps
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Fix, Map Edit, Modular

#278 [Helio] fixes SM chamber
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Fix, Map Edit, Modular

#276 Bloodsuckers: Archive of the Kindred
  code/___fulp_defines/fulp_defines.dm
  code/game/gamemodes/objective.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/monsterhunter_event.dm
  fulp_modules/main_features/bloodsuckers/icons/bs_leftinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/bs_rightinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/stake_leftinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/stake_rightinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/vamp_obj.dmi
  tgui/packages/tgui/interfaces/KindredArchives.js
Labels: Feature

#280 Pubby update
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Modular

#279 Removes Beefmen's phobia
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
Labels: Balance, Modular

#283 hopefuly fixes malkavian (please tm first :) )
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/malkavian_revelations.json
Labels: Fix, Modular

#282 Race Ban Code Improvement [Not Modular... Yet?]
  code/___fulp_defines/fulp_defines.dm
  code/modules/admin/sql_ban_system.dm
  fulp_modules/Z_edits/race_bans/races.dm
  fulp_modules/global_vars.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
Labels: Code Improvement, Modular

#288 oh oops (malkavian 2)
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Balance, Modular

#291 copypaste hotfix
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
Labels: Modular, Quality of Life

#294 Updates list of TG edits
  fulp_modules/Z_edits/tg_edits.md
  fulp_modules/main_features/bloodsuckers/readme.MD
Labels: Documentation, Modular

#285 Deputy Update 4: Full-departmental Deputies & Secbelt
  code/game/machinery/computer/crew.dm
  code/modules/jobs/jobs.dm
  fulp_modules/features/fulp_clothing/digitigrade/code/digi_lizard.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
  fulp_modules/main_features/jobs/brigdoc/code/landmark.dm
  fulp_modules/main_features/jobs/deputy/code/deputy.dm
  fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm
Labels: Balance, Quality of Life

#284 Secure coffin armour buff
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
Labels: Balance, Modular

#300 re-adds Fulp Chain of Command
  code/controllers/subsystem/job.dm
  fulp_modules/Z_edits/tg_edits.md
Labels: Fix

#296 Improved readme
  fulp_modules/readme.md
Labels: Documentation, Modular

#303 Making Selene better
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Balance, Code Improvement, Feature, Fix, Map Edit, Modular, Quality of Life, good first issue

#305 Deputy bloodsucker hotfix
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
Labels: Fix, Modular
