Repository fulpstation/fulpstation, pull requests merged in 2021-04, with the labels that each got.

#69 [Ready] Toys and food.
  fulp_modules/containor_init/vending_init.dm
  fulp_modules/food/code/food.dm
  fulp_modules/food/code/recipe.dm
  fulp_modules/food/icon/food.dmi
  fulp_modules/toys/code/toys.dm
  fulp_modules/toys/icon/toys.dmi
  fulp_modules/toys/sound/batong.ogg
  tgstation.dme
Labels: Feature, Modular, Sprites

#85 fixing things cause i'm dumb
  fulp_modules/food/code/recipe.dm
Labels: Fix

#64 Beefman Cytology Tutorial Spawner
  _maps/RandomRuins/IceRuins/fulp_icemoon_surface_cyto_nospace.dmm
  fulp_modules/beefman_port/code/modules/mob/beefman_clothing.dm
  fulp_modules/beefman_port/icons/mob/clothing/beefclothing.dmi
  fulp_modules/beefman_port/icons/mob/clothing/beefclothing_worn.dmi
  fulp_modules/cytology_spawner/beefcyto.dm
  tgstation.dme
Labels: Map Edit, Modular

#86 Prisioner Wintercoat 2 - please work this time
  fulp_modules/container_init/machine_init.dm
  fulp_modules/fulp_clothing/wintercoats/code/wintercoats.dm
  fulp_modules/fulp_clothing/wintercoats/icons/wintercoat_lefthand.dmi
  fulp_modules/fulp_clothing/wintercoats/icons/wintercoat_righthand.dmi
  fulp_modules/fulp_clothing/wintercoats/icons/wintercoathoods.dmi
  fulp_modules/fulp_clothing/wintercoats/icons/wintercoats.dmi
  fulp_modules/fulp_clothing/wintercoats/icons/wintercoats_icons.dmi
  tgstation.dme
Labels: Modular, Sprites

#87 Nightmares arent smart
  fulp_modules/nightmare_edit/nightmare.dm
  tgstation.dme
Labels: Balance, Modular

#91 fixes dumb misspelling
  fulp_modules/fulp_clothing/wintercoats/code/wintercoats.dm
Labels: Fix

#88 Deputies
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/crew.dm
  code/modules/jobs/jobs.dm
  config/jobs.txt
  fulp_modules/beefman_port/code/modules/mob/beefman.dm
  fulp_modules/beefman_port/code/modules/mob/beefman_clothing.dm
  fulp_modules/beefman_port/icons/mob/clothing/beefclothing.dmi
  fulp_modules/beefman_port/icons/mob/clothing/beefclothing_worn.dmi
  fulp_modules/fulp_clothing/digitigrade/outfit/digi_lizard.dm
  fulp_modules/global_vars.dm
  fulp_modules/jobs/antag_protection_overwrites.dm
  fulp_modules/jobs/brigdoc/code/dynamic.dm
  fulp_modules/jobs/brigdoc/code/gamemode_overwrite.dm
  fulp_modules/jobs/brigdoc/code/landmark.dm
  fulp_modules/jobs/brigdoc/readme.MD
  fulp_modules/jobs/cards.dmi
  fulp_modules/jobs/deputy/code/_deputy_defines.dm
  fulp_modules/jobs/deputy/code/deputy.dm
  fulp_modules/jobs/deputy/code/deputy_clothing.dm
  fulp_modules/jobs/deputy/code/deputy_grab.dm
  fulp_modules/jobs/deputy/deputy_clothing/deputy_clothes.dmi
  fulp_modules/jobs/deputy/deputy_clothing/head_icons.dmi
  fulp_modules/jobs/deputy/deputy_clothing/head_worn.dmi
  fulp_modules/jobs/deputy/deputy_clothing/ties_icons.dmi
  fulp_modules/jobs/deputy/deputy_clothing/ties_worn.dmi
  fulp_modules/jobs/deputy/deputy_clothing/under_worn.dmi
  fulp_modules/jobs/huds.dmi
  fulp_modules/jobs/readme.MD
  tgstation.dme
Labels: Feature

#96 Attempts to fix Beefmen
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  config/game_options.txt
  fulp_modules/beefman_port/code/_DEFINES/beefman_defines.dm
  fulp_modules/beefman_port/code/modules/mob/beefman.dm
  fulp_modules/beefman_port/icons/mob/beefman_bodyparts.dmi
Labels: Fix

#90 [MODULAR] [READY] Departmental Emergency Response Teams
  fulp_modules/departmental_ert/code/advanced_equipment.dm
  fulp_modules/departmental_ert/code/antag_datum.dm
  fulp_modules/departmental_ert/code/ert_datum.dm
  fulp_modules/departmental_ert/code/ert_outfit.dm
  fulp_modules/departmental_ert/code/hardsuits.dm
  fulp_modules/departmental_ert/code/procs.dm
  fulp_modules/departmental_ert/icons/hardsuit.dmi
  fulp_modules/departmental_ert/icons/hardsuit_worn.dmi
  fulp_modules/departmental_ert/sounds/home_depot.ogg
  fulp_modules/global_vars.dm
  tgstation.dme
Labels: Feature, Modular

#92 Upstream bot
  fulp_modules/malfunction_bot/upstream_bot.dm
  fulp_modules/malfunction_bot/upstream_prefix.txt
  tgstation.dme
Labels: Feature, Modular

#99 Ports over the BYOND Hub's MOTD configs
  code/game/world.dm
  config/config.txt
  fulp_modules/fulp_configs/code/ambience.dm
  fulp_modules/fulp_configs/code/sound.dm
  fulp_modules/fulp_configs/fulp_config.dm
  fulp_modules/fulp_configs/fulp_world.dm
  fulp_modules/fulp_configs/sound/Fulp_Piano.ogg
  fulp_modules/fulp_configs/sound/Fulp_Piano_Old.ogg
  fulp_modules/fulp_configs/sound/Fulp_Uhoh_Stinky.ogg
  fulp_modules/fulp_configs/sound/i_got_banned_on_fulpstation.ogg
  fulp_modules/fulp_configs/sound/spacepad.ogg
  tgstation.dme
Labels: Fix

#89 Chain of Command edit
  code/controllers/subsystem/job.dm
Labels: Quality of Life

#103 Removes Command/Deputy/Brig Doc Antags
  fulp_modules/jobs/antag_protection_overwrites.dm
Labels: Modular, Quality of Life

#98 Adds a Scientific Department ID to the RD's locker
  fulp_modules/container_init/machine_init.dm
  fulp_modules/science_budget/readme.MD
  fulp_modules/science_budget/science_budget.dm
  tgstation.dme
Labels: Feature, Modular

#100 [READY] Brig Physician Tweaks
  fulp_modules/beefman_port/code/modules/mob/beefman_clothing.dm
  fulp_modules/jobs/brigdoc/code/beacon.dm
  fulp_modules/jobs/brigdoc/code/brigdoc.dm
  fulp_modules/jobs/brigdoc/code/brigdoc_clothing.dm
  fulp_modules/jobs/brigdoc/code/cargo.dm
  fulp_modules/jobs/brigdoc/code/medkit.dm
  fulp_modules/jobs/brigdoc/icons/medkit.dmi
  fulp_modules/jobs/brigdoc/icons/medkit_lefthand.dmi
  fulp_modules/jobs/brigdoc/icons/medkit_righthand.dmi
  tgstation.dme
Labels: Balance, Modular

#101 Deputy update
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/jobs/brigdoc/code/landmark.dm
  fulp_modules/jobs/deputy/code/deputy.dm
  fulp_modules/jobs/deputy/code/deputy_block.dm
  fulp_modules/jobs/deputy/code/deputy_clothing.dm
  fulp_modules/jobs/deputy/code/deputy_grab.dm
  fulp_modules/jobs/deputy/deputy_clothing/ties_worn.dmi
  tgstation.dme
Labels: Modular, Quality of Life

#108 Update ID trims for Brig Doc and Deputy
  fulp_modules/jobs/cards.dmi
Labels: Fix

#111 Fixes broken stuff
  fulp_modules/jobs/deputy/code/deputy.dm
  fulp_modules/jobs/deputy/code/deputy_block.dm
Labels: Fix

#106 Fixes command antag because SOMEONE (totally not me) didnt do it properly
  fulp_modules/jobs/antag_protection_overwrites.dm
Labels: Fix, Modular

#110 Beefmen Phobetor Tear Resprite
  fulp_modules/beefman_port/icons/phobetor_tear.dmi
Labels: Modular, Sprites

#116 Bloodsucker changes
  fulp_modules/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
  fulp_modules/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/bloodsuckers/code/powers/haste.dm
  fulp_modules/bloodsuckers/code/powers/lunge.dm
  fulp_modules/bloodsuckers/code/powers/masquerade.dm
Labels: Fix, Modular

#113 Fixes plasmaman deputy helmet
  fulp_modules/jobs/deputy/deputy_clothing/head_icons.dmi
  fulp_modules/jobs/deputy/deputy_clothing/head_worn.dmi
Labels: Fix, Modular, Sprites

#117 Makes the batong fit on the belt slot & fixes some grammar.
  fulp_modules/toys/code/toys.dm
Labels: Feature, Grammar/Spelling, Modular

#119 Fixes bloodsucker's colorblindness
  fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#112 Cult stun nerf, but modular, and without the zealot's buff
  fulp_modules/cult_edit/cult_edit.dm
  tgstation.dme
Labels: Balance, Modular

#123 Resprites fulpstation food to be consistent with the tg upstream.
  fulp_modules/food/icon/food.dmi
Labels: Modular, Sprites

#120 Improves Bloodsucker objective code slightly
  code/game/gamemodes/objective.dm
  fulp_modules/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/bloodsuckers/code/gamemodes/traitorsucker_gamemode.dm
  fulp_modules/bloodsuckers/code/readme.MD
Labels: Feature

#122 science deputy medipens now contain a sane amount of mutadone
  fulp_modules/jobs/deputy/code/deputy.dm
  fulp_modules/jobs/deputy/code/deputy_clothing.dm
Labels: Balance, Modular

#109 Adds SeleneStation
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/selenestation.json
  _maps/shuttles/arrival_selene.dmm
  _maps/shuttles/cargo_selene.dmm
  _maps/shuttles/emergency_selene.dmm
  _maps/shuttles/mining_selene.dmm
  config/maps.txt
  fulp_modules/fulp_shuttles/fulp_shuttles.dm
  tgstation.dme
Labels: Feature, Modular

#125 Halloween fix
  fulp_modules/halloween_event/costumes_2019/jo_costumes.dmi
  fulp_modules/halloween_event/costumes_2020/costumes_world (1).dmi
  fulp_modules/halloween_event/costumes_2020/daft_frank.dm
  fulp_modules/halloween_event/costumes_2020/fixedskeleton3 (1).dmi
  fulp_modules/halloween_event/costumes_2020/flowercrown2 (1).dmi
  fulp_modules/halloween_event/costumes_2020/frog_worn.dmi
  fulp_modules/halloween_event/costumes_2020/power_ranger_worn.dmi
  fulp_modules/halloween_event/costumes_2020/princess.dm
  fulp_modules/halloween_event/costumes_2020/princess_worn.dmi
Labels: Fix, Modular, Sprites

#128 when the grammar mistake
  fulp_modules/toys/code/toys.dm
Labels: Grammar/Spelling, Modular

#124 Deputy update 2
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/jobs/cards.dmi
  fulp_modules/jobs/deputy/code/deputy.dm
  fulp_modules/jobs/deputy/code/deputy_block.dm
  fulp_modules/jobs/deputy/code/deputy_clothing.dm
  fulp_modules/jobs/deputy/deputy_clothing/radio.dmi
  fulp_modules/jobs/deputy/deputy_clothing/ties_icons.dmi
  fulp_modules/jobs/deputy/deputy_clothing/ties_worn.dmi
Labels: Balance, Modular

#127 Fixes hunter-fu and makes Bloodsuckers/Monster Hunters/Vassals, antag bannable
  code/modules/admin/sql_ban_system.dm
  fulp_modules/bloodsuckers/code/gamemodes/bloodsucker_gamemode.dm
  fulp_modules/bloodsuckers/code/monster_hunter/hunterfu.dm
  fulp_modules/bloodsuckers/code/readme.MD
Labels: Fix

#115 Redoing safety moth
  fulp_modules/departmental_ert/code/antag_datum.dm
  fulp_modules/departmental_ert/code/ert_datum.dm
  fulp_modules/departmental_ert/code/ert_outfit.dm
  fulp_modules/departmental_ert/code/hardsuits.dm
  fulp_modules/departmental_ert/code/procs.dm
Labels: Feature, Modular

#130 Doesnt make nightmares dumb unless its an actual nightmare
  fulp_modules/edits/nightmare_edit/nightmare.dm
Labels: Fix, Modular

#136 Minor Selene fixes
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/shuttles/emergency_selene.dmm
Labels: Map Edit, Modular

#139 Security crowbars but with less shitcode
  fulp_modules/ZFulpcode/modules/jobs/inventories.dm
  tgstation.dme
Labels: Fix, Modular

#140 Selene fixes
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#126 Fixes double Sol, removes Bloodsucker Gamemode + other fixes.
  code/__DEFINES/role_preferences.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/main_features/bloodsuckers/code/gamemodes/bloodsucker_gamemode.dm
  fulp_modules/main_features/bloodsuckers/code/gamemodes/monsterhunter_gamemode.dm
  fulp_modules/main_features/bloodsuckers/code/gamemodes/traitorsucker_gamemode.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  tgstation.dme
Labels: Fix, Modular
