Repository fulpstation/fulpstation, pull requests merged in 2021-08, with the labels that each got.

#289 Bloodsucker fixes
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
Labels: Fix, Modular

#301 Brig Physician's return of Sec office access & Sec lockers require ACCESS_WEAPONS
  fulp_modules/Z_edits/container_init/closet_init.dm
  fulp_modules/Z_edits/container_init/vendor_init.dm
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm
  tgstation.dme
Labels: Balance, Modular

#302 I was forced to do this
  fulp_modules/features/prison_kitchen/hos_prefix.txt
Labels: Modular, Quality of Life

#307 Documents mapping TG edit and moves tg_edits to fulp_modules
  fulp_modules/tg_edits.md
Labels: Documentation, Modular

#309 Update readme.md
  fulp_modules/readme.md
Labels: Documentation, Modular

#308 Safety moth again
  fulp_modules/features/ert/code/advanced_equipment.dm
  fulp_modules/features/ert/code/antag_datum.dm
  fulp_modules/features/ert/code/ert_datum.dm
  fulp_modules/features/ert/code/ert_outfit.dm
  fulp_modules/features/ert/code/hardsuits.dm
  fulp_modules/features/ert/code/procs.dm
  fulp_modules/features/ert/code/safety_moth.dm
  tgstation.dme
Labels: Feature, Modular

#312 Fixes midround Bloodsuckers keeping mutations
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
Labels: Fix, Modular

#313 Selene permabrig attempt 2
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/features/prison_kitchen/_restaurant.dm
  fulp_modules/features/prison_kitchen/food_overwrites.dm
  fulp_modules/features/prison_kitchen/icons/bots.dmi
  fulp_modules/features/prison_kitchen/prefixes/hos_prefix.txt
  fulp_modules/features/prison_kitchen/prefixes/prisoner_prefix.txt
  fulp_modules/features/prison_kitchen/prefixes/rat_prefix.txt
  fulp_modules/features/prison_kitchen/prefixes/warden_prefix.txt
  fulp_modules/features/prison_kitchen/prison_bots.dm
Labels: Map Edit, Modular

#316 Deletes departmental lockers
  fulp_modules/Z_edits/container_init/closet_init.dm
  fulp_modules/Z_edits/removals/cryopod.dm
  fulp_modules/Z_edits/removals/security_lockers.dm
  tgstation.dme
Labels: Modular, Quality of Life

#317 Literally just disables Perma prisoners
  _maps/heliostation.json
  _maps/selenestation.json
Labels: Config, Modular, Quality of Life

#297 Removes Traitor/Wiz antag tips, organizes images for the rest
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/features/antag_tips/code/antag_tip_integration.dm
  fulp_modules/features/antag_tips/code/asset_cache.dm
  fulp_modules/features/antag_tips/html/imposter.html
  fulp_modules/features/antag_tips/html/traitor.html
  fulp_modules/features/antag_tips/html/wiz_apprentice.html
  fulp_modules/features/antag_tips/html/wizard.html
  fulp_modules/features/antag_tips/icons/headset.png
  fulp_modules/features/antag_tips/icons/pda.png
  fulp_modules/features/antag_tips/icons/pen.png
  fulp_modules/features/antag_tips/icons/scroll.png
  fulp_modules/features/antag_tips/icons/spellbook.png
  fulp_modules/features/antag_tips/icons/traitor.png
  fulp_modules/features/antag_tips/icons/wizard.png
Labels: Removal, Modular

#319 Curses Bloodsucker code
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_recipes.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/component_frenzy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/haste.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/bloodsuckers/code/powers/veil.dm
  tgstation.dme
Labels: Feature, Modular, Code Improvement

#320 Pubbystation and Selenestation updates
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/pubbystation.json
  _maps/selenestation.json
Labels: Map Edit, Quality of Life, Modular

#323 Race code now should work roundstart
  fulp_modules/Z_edits/nightmare_edit/nightmare.dm
  fulp_modules/Z_edits/race_bans/bans.dm
Labels: Fix, Modular

#325 Adds an Autodrobe to Selene dorms (attempt #2)
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#326 Fixing Race Code 2: Electric Boogaloo
  fulp_modules/Z_edits/race_bans/bans.dm
Labels: Modular, Code Improvement

#328 Minor map fixes around Selene
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#330 Adds module duplicators to Selene/Helio
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#332 Minor changes on the cytology spawner
  fulp_modules/mapping/ruins/icemoon/beefman_cytology/beef_cytology.dmm
Labels: Map Edit, Modular

#331 Adds beefman tutorial spawner pt2
  _maps/RandomRuins/SpaceRuins/beef_station.dmm
  fulp_modules/mapping/ruins/space/beefman_station/beef_station_stuff.dmi
  fulp_modules/mapping/ruins/space/beefman_station/beefman_station.dm
  tgstation.dme
Labels: Feature, Map Edit, Modular
