Repository fulpstation/fulpstation, pull requests merged in 2021-09, with the labels that each got.

#338 Bloodsuckers: Masquerade Update (Second attempt)
  code/___fulp_defines/fulp_defines.dm
  code/game/gamemodes/objective.dm
  code/modules/mob/living/carbon/human/examine.dm
  fulp_modules/Z_edits/antagdatum.dm
  fulp_modules/features/antag_tips/html/bloodsucker.html
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/component_frenzy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brujah.dm
  fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/haste.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/bloodsuckers/code/powers/veil.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/monsterhunter_event.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/monsterhunter_rulesets.dm
  fulp_modules/main_features/bloodsuckers/icons/actions_bloodsucker.dmi
  fulp_modules/main_features/bloodsuckers/icons/actions_tremere_bloodsucker.dmi
  fulp_modules/main_features/bloodsuckers/icons/bloodsucker_icons.dmi
  fulp_modules/main_features/bloodsuckers/icons/bs_leftinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/bs_rightinhand.dmi
  fulp_modules/main_features/bloodsuckers/icons/vamp_obj.dmi
  tgstation.dme
Labels: Feature

#339 deputy config stuff
  code/controllers/subsystem/job.dm
  code/game/machinery/computer/crew.dm
  config/game_options.txt
  config/jobs.txt
  fulp_modules/features/clothing/digitigrade/code/digi_lizard.dm
  fulp_modules/fulp_configs/code/fulp_config.dm
  fulp_modules/global_vars.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/main_features/jobs/brigdoc/code/landmark.dm
  fulp_modules/main_features/jobs/deputy/code/deputy.dm
  fulp_modules/main_features/jobs/huds.dmi
Labels: Fix, Config

#336 Removes deputy's mindshield
  fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm
Labels: Balance, Modular

#340 [Selene] adds a door between Chapel and Library
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#343 [MDB IGNORE] Pubby update
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit

#341 bloodsucker objective quickfix
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
Labels: Fix, Modular

#344 Allows bodycams to be worn on any jumpsuit
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Feature, Modular

#345 Adds two Fnaf plushies
  fulp_modules/features/toys/code/toys.dm
  fulp_modules/features/toys/icons/toys.dmi
  fulp_modules/features/toys/sound/jumpscare.ogg
Labels: Feature, Sprites, Modular

#347 Gives Bodycameras Their Own Sprite
  fulp_modules/features/clothing/body_cameras/body_camera.dm
  fulp_modules/features/clothing/body_cameras/bodycamera.dmi
  fulp_modules/features/clothing/body_cameras/readme.md
Labels: Sprites, Modular

#352 Adds runtimestation to map rotation
  config/maps.txt
Labels: DO NOT MERGE

#346 codebase improvements
  fulp_modules/Z_edits/cult_edit/stun.dm
  fulp_modules/features/clothing/digitigrade/code/digi_shoes.dm
  fulp_modules/features/clothing/halloween/costumes_2020/gnome.dm
  fulp_modules/features/clothing/wintercoats/code/wintercoats.dm
  fulp_modules/features/ert/code/ert_outfit.dm
  fulp_modules/features/ert/code/safety_moth.dm
  fulp_modules/main_features/beefmen/code/modules/__DEFINES/beefman_defines.dm
  fulp_modules/main_features/beefmen/code/modules/mob/beefman.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_guardian.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/main_features/bloodsuckers/code/monster_hunter/hunterfu.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc.dm
  fulp_modules/main_features/jobs/brigdoc/code/brigdoc_clothing.dm
  fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm
  fulp_modules/main_features/mentorhelp/follow.dm
  fulp_modules/mapping/ruins/space/beefman_station/beefman_station.dm
Labels: Code Improvement

#348 Dominate: Better player feedback and fixes
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/main_features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
Labels: Fix, Modular

#353 Job unlock overwrite
  fulp_modules/Z_edits/fulp_jobs/unlock_times.dm
  tgstation.dme
Labels: Balance, Modular

#355 Fixes Malkavian admin loggings
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#357 Standardizes fulp edits (+removes a TG edit from mentorhelp)
  _maps/_basemap.dm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/datums/hud.dm
  code/game/area/areas/shuttles.dm
  code/game/gamemodes/objective.dm
  code/game/machinery/computer/crew.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  fulp_modules/Z_edits/preferences/_fulp_preferences.dm
  fulp_modules/fulp_configs/code/sound.dm
  fulp_modules/main_features/beefmen/code/modules/language/russian.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/mentorhelp/ahelp_reject.dm
  fulp_modules/main_features/mentorhelp/readme.MD
  fulp_modules/mapping/plaques/commission_plaques.dm
  fulp_modules/tg_edits.md
  tools/build/build.js
Labels: Code Improvement

#356 Modularizes space ruins
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/features/clothing/neck/neck.dm
  fulp_modules/features/clothing/neck/neck.dmi
  fulp_modules/features/toys/code/plushies.dm
  fulp_modules/features/toys/icons/toys.dmi
  fulp_modules/mapping/ruins/code.dm
  fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm
  fulp_modules/mapping/ruins/space/beef_station.dmm
  fulp_modules/mapping/ruins/space/beefman_station/beef_station_stuff.dmi
  fulp_modules/mapping/ruins/space/beefman_station/beefman_station.dm
  tgstation.dme
Labels: Modular, Code Improvement

#359 Moves bodycamera to armor vests
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Balance, Modular

#361 Fix an oversight on miner unlock and add QM to the list
  fulp_modules/Z_edits/fulp_jobs/unlock_times.dm
Labels: Fix, Modular

#360 Bloodsucker further code improvements
  code/___fulp_defines/bloodsucker_defines.dm
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_ui.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/component_frenzy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brawn.dm
  fulp_modules/main_features/bloodsuckers/code/powers/brujah.dm
  fulp_modules/main_features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/main_features/bloodsuckers/code/powers/distress.dm
  fulp_modules/main_features/bloodsuckers/code/powers/feed.dm
  fulp_modules/main_features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/main_features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/main_features/bloodsuckers/code/powers/haste.dm
  fulp_modules/main_features/bloodsuckers/code/powers/lunge.dm
  fulp_modules/main_features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/main_features/bloodsuckers/code/powers/mesmerize.dm
  fulp_modules/main_features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/main_features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/main_features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/main_features/bloodsuckers/code/powers/trespass.dm
  fulp_modules/main_features/bloodsuckers/code/powers/veil.dm
  tgstation.dme
Labels: Modular, Code Improvement

#363 beefmen tgui preference stuff
  fulp_modules/Z_edits/preferences/beefman_preferences.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/species/beefman.ts
Labels: Quality of Life

#364 Removes static spawn maint pills from Selene and replaces them with random maint loot spawners
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#362 Modularizes a ton of Fulp edits within TG code
  code/__DEFINES/atom_hud.dm
  code/__HELPERS/global_lists.dm
  code/___fulp_defines/bloodsucker_defines.dm
  code/controllers/subsystem/job.dm
  code/datums/hud.dm
  code/game/machinery/computer/crew.dm
  code/modules/client/client_procs.dm
  fulp_modules/fulp_configs/code/fulp_world.dm
  fulp_modules/main_features/beefmen/code/beefman_integration.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/main_features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/main_features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/main_features/jobs/deputy/code/deputy_clothing.dm
  fulp_modules/main_features/jobs/job_integration.dm
  fulp_modules/main_features/jobs/readme.MD
  fulp_modules/main_features/mentorhelp/mentor_clientprocs.dm
  fulp_modules/tg_edits.md
Labels: Modular, Code Improvement
