Repository fulpstation/fulpstation, pull requests merged in 2022-11, with the labels that each got.

#842 Ports the halloween races fix from tg (#70874)
  code/__HELPERS/names.dm
  code/controllers/subsystem/communications.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/ticker.dm
  code/game/machinery/computer/arcade/arcade.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/teleporter.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/implants/implant_mindshield.dm
  code/game/objects/structures/signs/signs_interactive.dm
  code/game/turfs/closed/minerals.dm
  code/modules/antagonists/brainwashing/brainwashing.dm
  code/modules/antagonists/cult/runes.dm
  code/modules/antagonists/slaughter/slaughter.dm
  code/modules/assembly/flash.dm
  code/modules/clothing/suits/ghostsheet.dm
  code/modules/events/_event.dm
  code/modules/events/aurora_caelus.dm
  code/modules/events/holiday/xmas.dm
  code/modules/events/meteor_wave.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mod/modules/modules_antag.dm
  code/modules/paperwork/paperbin.dm
  code/modules/reagents/reagent_dispenser.dm
Labels: Fix

#841 Halloween outfits 2022
  fulp_modules/features/halloween/2022/2022_icons.dmi
  fulp_modules/features/halloween/2022/2022_icons_worn.dmi
  fulp_modules/features/halloween/2022/costumes.dm
  fulp_modules/features/halloween/_code.dm
  tgstation.dme
Labels: Feature, Sprites, Modular

#837 Helio Sec Rework Part 2/2: Perma and Courtroom
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/shuttles/labour_helio.dmm
  fulp_modules/mapping/areas/areas.dm
  fulp_modules/mapping/areas/icons.dmi
  fulp_modules/mapping/shuttles/map_templates.dm
  fulp_modules/mapping/station_objects/decals.dm
Labels: Feature, Map Edit, Modular

#849 admin logging infil objectives
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Modular, Administration

#848 Fixes cruelty squad gloves
  fulp_modules/features/halloween/2022/2022_icons.dmi
  fulp_modules/features/halloween/2022/2022_icons_worn.dmi
  fulp_modules/features/halloween/2022/costumes.dm
Labels: Fix, Sprites, Modular

#850 infil antag ui gets updated automatically with new objectives without having to refresh
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Fix, Modular
