Repository fulpstation/fulpstation, pull requests merged in 2022-01, with the labels that each got.

#448 [Solitaire] Science Overhaul
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Merge Conflict

#446 Bloodsuckers: Tremere Pack
  code/___fulp_defines/bloodsucker_defines.dm
  fulp_modules/features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_ui.dm
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/bloodsuckers/icons/bloodsucker_icons.dmi
  tgstation.dme
Labels: Fix, Modular, Code Improvement

#450 Solitare: Sec buzz-in and runed metal removal
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Modular

#451 removes merge conflict marker
  fulp_modules/mapping/ruins/space/beef_station.dmm
Labels: Map Edit, Fix, Modular

#453 Fixes stuff from the solitaire feedback thread plus bridge pipes and also redoes like half of engi/atmos piping why were half of the pipes inside walls for no reason even
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix, Modular

#456 fixes beefmen tear qdel'ing
  fulp_modules/features/species/beefmen/phobetor_trauma.dm
Labels: Fix, Modular

#455 Msay and mhelp QOL (Pinging, hyperlinks)
  fulp_modules/features/mentors/mentorhelp.dm
  fulp_modules/features/mentors/mentorpm.dm
  fulp_modules/features/mentors/mentorsay.dm
Labels: Feature, Modular

#457 Brig Physician playtime now grants mecical exp instead of security
  fulp_modules/features/jobs/brigdoc/brigdoc.dm
Labels: Quality of Life, Modular

#459 Remove digitigrade shoes from some lockers.
  fulp_modules/Z_edits/inititalize_edits/closet_init.dm
Labels: Removal, Modular

#460 Fixes the Heliostation blue law office privacy button
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#458 Bloodsucker cooldown fixes
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
Labels: Fix, Modular

#462 Fix small atmos issue on Beeftology station.
  fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm
Labels: Map Edit, Fix, Modular

#463 Solitaire fixes
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix, Modular

#464 Brings back Summon Dance Floor
  fulp_modules/features/spells/fulp_spellbook.dm
  fulp_modules/features/spells/fulp_spells.dm
  tgstation.dme
Labels: Feature, Modular

#465 Beef station music
  fulp_modules/mapping/helpers/areas.dm
  fulp_modules/sounds/sound/ambience/beef_station.ogg
Labels: Feature, Modular

#470 removes mentions of vampires in bloodsuckers
  code/___fulp_defines/bloodsucker_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  fulp_modules/features/antag_tips/html/vassal.html
  fulp_modules/features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/vampiric.dm
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/bloodsuckers/code/powers/veil.dm
  fulp_modules/features/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/features/bloodsuckers/icons/actions_bloodsucker.dmi
  fulp_modules/features/bloodsuckers/icons/bloodsucker_huds.dmi
  fulp_modules/features/bloodsuckers/icons/bloodsucker_obj.dmi
  fulp_modules/features/bloodsuckers/icons/bloodsucker_obj_64.dmi
Labels: Quality of Life, Modular

#473 Beefman tongue INSERTION REMOVAL
  fulp_modules/features/species/beefmen/mob/beefman.dm
Labels: Feature, Modular

#475 makes science actually have an APC
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#477 Fixes the helio bar stools facing the wrong way
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#468 Solitaire - Brig and Perma overhaul
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/map_files/SolitaireStation/Solitairestation.dmm
  _maps/solitairestation.json
Labels: Map Edit, Modular

#479 Bloodsucker: Mesmerize fix & misc code improvement
  fulp_modules/features/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/brujah.dm
  fulp_modules/features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/features/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/_powers_targeted.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/haste.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/features/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/bloodsuckers/code/powers/veil.dm
Labels: Fix, Modular, Code Improvement

#481 Deputies: Lockers & Beret destroy objectives
  fulp_modules/Z_edits/antag_objectives.dm
  fulp_modules/Z_edits/security_lockers.dm
  fulp_modules/features/jobs/deputy/deputy_closet.dm
  fulp_modules/features/jobs/deputy/deputy_gear.dm
  fulp_modules/features/jobs/icons/deputy_lockers.dmi
  tgstation.dme
Labels: Feature, Modular

#488 Fixes Solitaire runtimes + missing APCs
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix, Modular

#489 Fixes feed (standardizes BS power code so it doesn't happen again in the future)
  fulp_modules/features/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/bloodsuckers/code/powers/brujah.dm
  fulp_modules/features/bloodsuckers/code/powers/cloak.dm
  fulp_modules/features/bloodsuckers/code/powers/distress.dm
  fulp_modules/features/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/bloodsuckers/code/powers/monstertrack.dm
  fulp_modules/features/bloodsuckers/code/powers/recuperate.dm
Labels: Fix, Modular

#490 [Solitaire/Selene] Fixes Deputy lockers
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix, Modular

#491 [Helio] Stops the HoS office from getting depressurized most rounds.
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Quality of Life, Modular

#492 Fixes the best clan
  fulp_modules/features/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#493 Removes wings.
  fulp_modules/features/moth_customization/code/moth_antennae.dm
  fulp_modules/features/moth_customization/code/moth_wings.dm
  fulp_modules/features/moth_customization/icons/fulp_moth_antennae.dmi
  fulp_modules/features/moth_customization/icons/fulp_moth_wings.dmi
Labels: Removal, Modular

#494 Fixes beefman spawner names (name + role name)
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/mapping/ruins/icemoon/beefman_cytology/beefcyto_spawner.dm
Labels: Fix, Modular

#484 Fixes non-existant icon for the deadcell hardhat
  fulp_modules/features/halloween/2021/costumes.dm
Labels: Fix, Modular

#485 Organizes all Fulp cargo crates into one folder/file and adds a FNAF plushy crate to cargo
  fulp_modules/features/cargo/cargo.dm
  fulp_modules/features/halloween/cargo_costumes.dm
  tgstation.dme
Labels: Feature, Modular

#482 Bloodthrones amplify Bloodsucker speech
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
Labels: Quality of Life, Modular

#496 Solitaires' Solitaire Station disposals overhaul, fixes, and tweaks.
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix, Modular
