Repository fulpstation/fulpstation, pull requests merged in 2022-03, with the labels that each got.

#541 solitaire arrivals fixes + maint loot removal
  _maps/map_files/SolitaireStation/Solitairestation.dmm
Labels: Map Edit, Fix

#521 [MDB IGNORE] Remaps Selene Science
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#542 Fixes stakes + Archives code improvement
  code/___fulp_defines/bloodsucker_defines.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  tgui/packages/tgui/interfaces/KindredArchives.js
Labels: Fix, Modular, Code Improvement

#543 Fixes pubby's yellow stripes decal corner being weird and stuff
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Fix, Modular

#545 Fixes deputies getting empty pizza in the mail today
  fulp_modules/features/jobs/deputy/_deputy.dm
Labels: Fix, Modular

#547 fixes deputy beret objectives
  fulp_modules/features/jobs/deputy/deputy_gear.dm
Labels: Fix, Modular

#548 Removes solitaire
  _maps/_basemap.dm
  _maps/map_files/SolitaireStation/Solitairestation.dmm
  _maps/solitairestation.json
  fulp_modules/tg_edits.md
Labels: Map Edit, Removal, Modular

#550 Refactors bodycameras into an Element
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Modular, Code Improvement

#552 Rearranges Helio & Selene Tcomms to make more sense for the 3 people that know how tcomms work
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#553 Cheaper living beefplushie and grammer fixes
  fulp_modules/features/antagonists/traitor/uplink_items/race_restricted.dm
Labels: Balance, Modular, Grammar/Spelling

#554 Beefmen Now Take 20% Extra Damage Instead of 2%
  fulp_modules/features/species/beefmen/mob/beefman.dm
Labels: Fix, Modular

#555 FIXES meatman limb duplication glitch
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/features/species/beefmen/mob/beefman_limbs.dm
Labels: Fix, Modular

#556 Fixes Selene Station science supply order console
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#557 Predatory lunge rework
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm
Labels: Balance, Modular

#558 Fixes MH's not spawning
  fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm
Labels: Fix, Modular

#559 Feed rework
  code/___fulp_defines/bloodsucker_defines.dm
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
Labels: Balance, Modular

#560 Fixes trash spawning in structures on prison shuttle
  fulp_modules/features/prison/prison_shuttle/prison_shuttle_template.dm
Labels: Fix, Modular

#562 fixes lunge
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
Labels: Fix, Modular

#564 monsterhunters now take all antags into account
  fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm
Labels: Balance, Modular

#566 makes body cams a component
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Modular, Code Improvement

#536 Fulp map toxins are cursed
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Modular

#551 Removes Brig Physician
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/_global_vars.dm
  fulp_modules/features/antagonists/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/features/antagonists/ert/code/safety_moth.dm
  fulp_modules/features/cargo/cargo.dm
  fulp_modules/features/clothing/digitigrade/code/digi_lizard.dm
  fulp_modules/features/jobs/brigdoc/beacon.dm
  fulp_modules/features/jobs/brigdoc/brigdoc.dm
  fulp_modules/features/jobs/brigdoc/brigdoc_clothing.dm
  fulp_modules/features/jobs/brigdoc/medkit.dm
  fulp_modules/features/jobs/icons/cards.dmi
  fulp_modules/features/jobs/icons/clothing_icons.dmi
  fulp_modules/features/jobs/icons/clothing_worn.dmi
  fulp_modules/features/jobs/icons/huds.dmi
  fulp_modules/features/jobs/icons/medkit.dmi
  fulp_modules/features/jobs/icons/medkit_lefthand.dmi
  fulp_modules/features/jobs/icons/medkit_righthand.dmi
  fulp_modules/features/jobs/job_integration.dm
  fulp_modules/features/jobs/landmark.dm
  fulp_modules/features/species/beefmen/beefman_clothing.dm
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/features/species/icons/mob/clothing/beefclothing.dmi
  fulp_modules/features/species/icons/mob/clothing/beefclothing_worn.dmi
  tgstation.dme
Labels: Removal, Modular

#567 Adds fire alarm to helio sec hallway and windows to F/S maint
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Quality of Life, Modular

#569 Fixes some Pubby issues.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Fix, Modular

#570 fixes feeding off mice
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
Labels: Fix, Modular

#571 Small fix to Helio Permabrig + Fix to mail shuttles
  _maps/map_files/Heliostation/Heliostation.dmm
  code/___fulp_defines/fulp_defines.dm
  fulp_modules/features/prison/prison_shuttle/prison_mail.dm
  fulp_modules/features/prison/prison_shuttle/prison_shuttle_template.dm
Labels: Map Edit, Fix, Modular

#576 Fixes shaded bloodsuckers
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm
Labels: Fix, Modular
