Repository fulpstation/fulpstation, pull requests merged in 2022-08, with the labels that each got.

#745 Datumizing Bloodsucker Clans
  fulp_modules/_defines/bloodsuckers.dm
  fulp_modules/features/antagonists/antag_tips/code/asset_cache.dm
  fulp_modules/features/antagonists/antag_tips/html/bloodsucker.html
  fulp_modules/features/antagonists/antag_tips/icons/masquerade.png
  fulp_modules/features/antagonists/antag_tips/icons/vassalrack.png
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_hud.dm
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/assets/bloodsucker_assets.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_daylight.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_flaws.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_flavortext.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_malkavian.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_nosferatu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/monster_hunter/hunterfu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/brujah.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/cloak.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/distress.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/recuperate.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/brawn.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/haste.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/_powers_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm
  fulp_modules/features/antagonists/bloodsuckers/icons/actions_bloodsucker.dmi
  fulp_modules/features/antagonists/bloodsuckers/icons/clan_icons.dmi
  fulp_modules/tg_edits.md
  tgstation.dme
  tgui/packages/fulpui-patches/interfaces/AntagInfoBloodsucker.tsx
  tgui/packages/fulpui-patches/interfaces/KindredArchives.js
Labels: Modular, Code Improvement

#752 fixes pubbystation's CQC and prisoner slots
  _maps/pubbystation.json
Labels: Map Edit, Fix, Modular

#754 fixes runtime in infils
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
Labels: Fix, Modular

#761 Fixes Ventrue
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_coffin.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_ventrue.dm
Labels: Fix, Modular

#756 New clan icons
  fulp_modules/features/antagonists/bloodsuckers/icons/clan_icons.dmi
Labels: Sprites, Modular

#758 Fixes access problems with Selene
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#760 Fixes vampire examine showing up to non-vamps
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
Labels: Fix, Modular

#763 Ports the Bruhspace Anomaly
  fulp_modules/features/events/bruhspace_anomaly.dm
  fulp_modules/features/events/halloween.dm
  tgstation.dme
Labels: Feature, Modular

#764 Adds S.E.L.F faction to infiltrators
  fulp_modules/_defines/fulp_defines.dm
  fulp_modules/features/antagonists/infiltrators/icons/infils.dmi
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
  fulp_modules/strings/infiltrator/infiltrator_self.json
Labels: Feature, Modular

#765 reconnects turbine to smes on selenstation
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#766 Connects Helio Cargo to the pipenet
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#769 Fixes Persuasion rack
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
Labels: Fix, Modular

#770 Bloodsuckers lose blood when willingly removed
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
Labels: Fix, Modular

#771 Fixes Bloodsucker's antag info
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
Labels: Fix, Modular

#772 Fixes Ventrue getting infinite levels
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_ventrue.dm
Labels: Fix, Modular

#773 Logs infil radio gifts
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
Labels: Modular, Administration

#757 unique objective for animal rights activists infiltrators
  fulp_modules/features/antagonists/infiltrators/albino_gorilla.dm
  fulp_modules/features/antagonists/infiltrators/icons/gorilla.dmi
  fulp_modules/features/antagonists/infiltrators/icons/infils.dmi
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
  tgstation.dme
  tgui/packages/fulpui-patches/interfaces/InfilRadio.js
Labels: Feature, Sprites, Modular

#767 Lets admins chose infil faction on give Posted from my Galaxy A32.
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Feature, Modular, Administration

#775 Bump auxlua to 1.0.0
  auxlua.dll
Labels: Code Improvement

#777 Lets mentors use mentor manager
  fulp_modules/features/mentors/mentor_manager.dm
Labels: Fix, Modular, Administration

#778 Fixes bruhspace grammar
  fulp_modules/features/events/bruhspace_anomaly.dm
Labels: Grammar/Spelling

#789 Replaces custom objective for gorlex maurauderuresu
  fulp_modules/features/antagonists/infiltrators/icons/infils.dmi
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
  fulp_modules/features/antagonists/infiltrators/sounds/missile_alert.ogg
  tgui/packages/fulpui-patches/interfaces/MissilePhone.js
Labels: Feature, Fix, Modular

#794 prevents temporary vassals from being favoritized
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm
Labels: Fix, Modular

#779 Bruhspace event text is restored to mith's version
  fulp_modules/features/events/bruhspace_anomaly.dm
Labels: Modular, Grammar/Spelling

#797 fixes runtime when staking bloodsuckers
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/monster_hunter/hunterfu.dm
Labels: Fix, Modular

#798 allows admins to vassalize ppl
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
Labels: Quality of Life, Modular, Administration
