Repository fulpstation/fulpstation, pull requests merged in 2022-10, with the labels that each got.

#815 Removes an undocument balance change
  fulp_modules/Z_edits/heart.dm
  tgstation.dme
Labels: Revert, Balance, Modular

#811 Port Potato's Fix of Rendering Issue
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix, RED LABEL

#821 rewrites emag objective
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
Labels: Modular, Code Improvement

#822 Adds layer adapters to heliostation atmos gas chamber outlets
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Quality of Life, Modular

#819 replaces corporate climber theft objective with a new custom objective
  fulp_modules/features/antagonists/infiltrators/icons/infils.dmi
  fulp_modules/features/antagonists/infiltrators/infil_corpmarket.dm
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
  tgstation.dme
  tgui/packages/fulpui-patches/interfaces/InfilMarketUplink.js
Labels: Feature, Modular

#824 Heliostation QOL Changes, Mostly Medbay
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Quality of Life, Modular

#825 Helio evac second attempt
  _maps/heliostation.json
  _maps/shuttles/emergency_helio.dmm
  fulp_modules/mapping/shuttles/map_templates.dm
Labels: Feature, Map Edit, Modular

#831 Fixes hole in beef station
  fulp_modules/mapping/ruins/space/beef_station.dmm
Labels: Map Edit, Fix, Modular

#829 Modsuit Utility Modules
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Quality of Life, Modular

#830 nerfs infil secborgs
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
Labels: Balance, Modular

#835 Action Figures
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#839 October TGU 2
  code/modules/unit_tests/screenshots/screenshot_antag_icons_monsterhunter.png
Labels: Fix, TGU

#838 fixes vassal abilities
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/vassal_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/distress.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/recuperate.dm
Labels: Fix, Modular
