Repository fulpstation/fulpstation, pull requests merged in 2022-05, with the labels that each got.

#618 [TM First] Bloodsucker vassalization objective refactor and bugfix
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
Labels: Fix, Modular, Code Improvement

#626 fixes mnoster hunter grentexting
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/monsterhunter_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
Labels: Fix, Modular

#627 Swags Heliostation
  _maps/map_files/Heliostation/Heliostation.dmm
  fulp_modules/mapping/ruins/space/beef_station.dmm
Labels: Map Edit, Fix, Modular

#628 Makes traitor beefplushie actually work because i was a dumbass all along
  fulp_modules/features/antagonists/traitor/uplink_items/race_restricted.dm
Labels: Fix, Modular

#632 Adds body camera to sec vests
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Balance, Modular

#633 I added a SHUTTER in PHARMACY in PUBBY station.
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Modular

#639 infils fixes buncha shit
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Modular, Code Improvement

#643 A few map fixes
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/mapping/ruins/icemoon/beef_cytology.dmm
  fulp_modules/mapping/ruins/space/beef_station.dmm
  fulp_modules/mapping/shuttles/cargo/cargo_selene.dmm
Labels: Map Edit, Fix, Modular

#644 fix infiltrator preview icon on antag enabling panel
  fulp_modules/features/antagonists/infiltrators/infil_ruleset.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/antagonists/antagonists/ghostinfiltrator.ts
Labels: Fix, Modular

#612 blood-sucker-tgui - Adds a new tgui interface for the bloodsucker antag
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/tg_edits.md
  tgui/packages/fulpui-patches/index.js
  tgui/packages/fulpui-patches/interfaces/AntagInfoBloodsucker.tsx
  tgui/packages/fulpui-patches/package.json
  tgui/packages/tgui/routes.js
  tgui/yarn.lock
Labels: Quality of Life, Modular
