Repository fulpstation/fulpstation, pull requests merged in 2022-09, with the labels that each got.

#799 Unfucks selene ordnance
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#793 The Heliostation Engineering Shuffle
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Modular

#800 fixes ghost selection for gorilla spawning
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
Labels: Fix, Modular

#801 fixes runtime for SHADED bloodsuckers
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm
Labels: Fix, Modular

#802 Makes Ray a contributor
  fulp_modules/features/mentors/mentor_clientprocs.dm
Labels: Fix, Modular

#806 Post-shuffle heliostation fixes
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#795 readds security borgs
  fulp_modules/features/antagonists/infiltrators/icons/infils.dmi
  fulp_modules/features/antagonists/infiltrators/icons/robot.dmi
  fulp_modules/features/antagonists/infiltrators/icons/wormhole_left.dmi
  fulp_modules/features/antagonists/infiltrators/icons/wormhole_right.dmi
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Feature, Modular

#805 fixes the monsterhunter antagonist
  fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/monstertrack.dm
Labels: Fix, Modular

#809 Promotes Ray to contributor (FR)
  fulp_modules/features/mentors/mentor_clientprocs.dm
Labels: Fix, Modular

#812 Removes lightbulb on Pubbystation
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Fix, Modular

#813 Removed a door, fixed Captains offices access and HoP flash
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix, Modular

#810 fixes infils not greentexting cause of dagd
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
Labels: Fix, Modular

#818 Updates Fulp maps to some new TG standards and fixes some stuff
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#817 fixes bloodsucker shards capturing non existing ghosts
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/shaded_bloodsucker.dm
Labels: Fix, Modular

#816 Fixes two typos in the description and name of a jumpsuit
  fulp_modules/features/halloween/2021/costumes.dm
Labels: Modular, Grammar/Spelling

#820 dehardcodes the INFILRADIO UI
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  tgui/packages/fulpui-patches/interfaces/InfilRadio.js
Labels: Modular, Code Improvement
