Repository fulpstation/fulpstation, pull requests merged in 2022-06, with the labels that each got.

#645 Changes the detective's jobslots to 1 roundstart and 2 total
  fulp_modules/Z_edits/job_edits.dm
Labels: Balance, Modular

#649 book of kindred resprite
  fulp_modules/features/antagonists/bloodsuckers/icons/bs_leftinhand.dmi
  fulp_modules/features/antagonists/bloodsuckers/icons/bs_rightinhand.dmi
  fulp_modules/features/antagonists/bloodsuckers/icons/vamp_obj.dmi
Labels: Sprites, Modular

#651 Fixes our jobs lol
  fulp_modules/Z_edits/job_edits.dm
Labels: Fix, Modular

#653 fixes monstr huntr icon and corporate climber objectives
  fulp_modules/features/antagonists/bloodsuckers/code/rulesets/monsterhunter_event.dm
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
Labels: Fix, Modular

#656 Moves 2 fulp TGUIs to fulp TGUI folder
  fulp_modules/tg_edits.md
  tgui/packages/fulpui-patches/interfaces/KindredArchives.js
  tgui/packages/fulpui-patches/interfaces/RequestManagerFulp.js
Labels: Modular, Code Improvement

#658 Felinids, or anyone trying to become a felinid, now start with brain damage
  fulp_modules/Z_edits/felinid_edit.dm
  tgstation.dme
Labels: Feature, Modular

#660 Flow doesn't cost blood anymore
  fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
Labels: Fix, Modular

#667 Fixes our CI, Putting on cat ears gives just a bit more brain damage
  fulp_modules/Z_edits/felinid_edit.dm
Labels: Fix, Modular

#669 Lets cargo use their supply shuttle on selene
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#672 Saves our parallel map testing tests?
  fulp_modules/Z_edits/felinid_edit.dm
Labels: Fix, Modular

#655 Bloodsuckers can drink any blood (TG edit removal)
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/modules/antagonists/traitor/objectives/eyesnatching.dm
  code/modules/mob/living/carbon/human/examine.dm
  fulp_modules/Z_edits/felinid_edit.dm
  fulp_modules/features/antagonists/bloodsuckers/code/antagonists/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_crypt.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_integration.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objects.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/brujah.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/species/species_integration.dm
  fulp_modules/tg_edits.md
Labels: Modular, Code Improvement

#661 Fixes some misspellings in our codebase
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Modular, Grammar/Spelling

#662 Helio Medical Revamp
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Modular

#664 Advanced mulligan no bludgeon and it says its one use in its description
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
Labels: Balance, Modular

#666 adds sunglasses to helio office
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Balance, Modular

#668 fixes beefmen not bleeding
  fulp_modules/features/species/beefmen/mob/beefman.dm
Labels: Fix, Modular

#670 removes deputies
  fulp_modules/Z_edits/antag_objectives.dm
  fulp_modules/Z_edits/security_lockers.dm
  fulp_modules/_defines/fulp_defines.dm
  fulp_modules/_defines/traits.dm
  fulp_modules/features/antagonists/bloodsuckers/code/rulesets/bloodsucker_rulesets.dm
  fulp_modules/features/jobs/deputy/_deputy.dm
  fulp_modules/features/jobs/deputy/deputy_block.dm
  fulp_modules/features/jobs/deputy/deputy_closet.dm
  fulp_modules/features/jobs/deputy/deputy_gear.dm
  fulp_modules/features/jobs/deputy/deputy_skillchip.dm
  fulp_modules/features/jobs/huds.dm
  fulp_modules/features/jobs/icons/cards.dmi
  fulp_modules/features/jobs/icons/deputy_clothes.dmi
  fulp_modules/features/jobs/icons/deputy_lockers.dmi
  fulp_modules/features/jobs/icons/head_icons.dmi
  fulp_modules/features/jobs/icons/head_worn.dmi
  fulp_modules/features/jobs/icons/huds.dmi
  fulp_modules/features/jobs/icons/radio.dmi
  fulp_modules/features/jobs/icons/ties_icons.dmi
  fulp_modules/features/jobs/icons/ties_worn.dmi
  fulp_modules/features/jobs/icons/under_worn.dmi
  fulp_modules/features/jobs/job_integration.dm
  fulp_modules/features/jobs/landmark.dm
  fulp_modules/features/jobs/medipens.dm
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/fulp_world/_global_vars.dm
  tgstation.dme
Labels: Removal, Modular

#685 Modsuit & ERT code improvements
  fulp_modules/Z_edits/modsuits.dm
  fulp_modules/features/antagonists/ert/code/ert_outfit.dm
  fulp_modules/features/antagonists/ert/code/modsuits.dm
  tgstation.dme
Labels: Fix, Modular, Code Improvement

#686 Makes summon dance floor not appear as an offensive spell
  fulp_modules/features/spells/fulp_spellbook.dm
Labels: Fix, Modular

#687 Removes the free Close Quarter Cooking skillchip from the prison shuttle
  _maps/shuttles/prison_kitchen.dmm
Labels: Removal, Modular

#688 Allows prisoners to use the prison budget
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/features/prison/prison_cargo.dm
Labels: Fix, Modular

#689 Fixes our map json's job changes
  _maps/heliostation.json
  _maps/selenestation.json
Labels: Fix, Modular

#697 Improves beefman code significantly
  code/modules/mob/living/carbon/human/species.dm
  config/game_options.txt
  fulp_modules/_defines/fulp_defines.dm
  fulp_modules/_defines/species_defines.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm
  fulp_modules/features/species/beefmen/beefman_preferences.dm
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/features/species/beefmen/mob/beefman_accessories.dm
  fulp_modules/features/species/icons/mob/beefman_bodyparts.dmi
  fulp_modules/features/species/species_integration.dm
  fulp_modules/fulp_world/_global_vars.dm
  fulp_modules/tg_edits.md
  tgstation.dme
Labels: Fix, Modular, Code Improvement

#695 Fixes CI Part 2 (and texasman)
  code/modules/unit_tests/screenshots/screenshot_antag_icons_bloodsucker.png
  code/modules/unit_tests/screenshots/screenshot_antag_icons_bloodsuckerbreakout.png
  code/modules/unit_tests/screenshots/screenshot_antag_icons_infiltrator.png
  code/modules/unit_tests/screenshots/screenshot_antag_icons_monsterhunter.png
  code/modules/unit_tests/screenshots/screenshot_antag_icons_vampiricaccident.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_beefman.png
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_human_felinid_nobraindamage.png
  fulp_modules/features/halloween/2020/costumes.dm
  fulp_modules/features/species/species_integration.dm
  fulp_modules/tg_edits.md
Labels: Fix
