Repository fulpstation/fulpstation, pull requests merged in 2023-12, with the labels that each got.

#1073 Halloween Outfits 2023
  fulp_modules/features/halloween/2023/2023_icons.dmi
  fulp_modules/features/halloween/2023/2023_icons_left.dmi
  fulp_modules/features/halloween/2023/2023_icons_right.dmi
  fulp_modules/features/halloween/2023/2023_icons_worn.dmi
  fulp_modules/features/halloween/2023/costumes.dm
  fulp_modules/features/halloween/box.dmi
  fulp_modules/features/toys/code/plushies.dm
Labels: Feature, Modular

#1079 Bodycamera better feedback
  fulp_modules/features/clothing/body_cameras/body_camera.dm
Labels: Quality of Life, Modular, Grammar/Spelling

#1080 Ports a fix to cursed that slipped by the TGU
  code/datums/components/omen.dm
Labels: Fix

#1078 Selene Brig Edit
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  _maps/shuttles/labour_selene.dmm
  fulp_modules/mapping/shuttles/map_templates.dm
  fulp_modules/mapping/station_objects/machinery.dm
  tgstation.dme
Labels: Map Edit

#1081 Adds bigger art canvases to fulp maps
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit

#1085 fixes nightmares not being dumb
  fulp_modules/Z_edits/nightmare_edit.dm
Labels: Fix, Modular

#1084 Malkavian Dracula Flow 2 [For real this time]
  fulp_modules/strings/bloodsuckers/malkavian_revelations.json
Labels: Feature, Modular

#1087 Fixes heretic ascension
  fulp_modules/Z_edits/antag_edits/antag_datum.dm
  fulp_modules/Z_edits/antag_edits/heretic_ascension_fix.dm
  tgstation.dme
Labels: Fix, Modular
