Repository fulpstation/fulpstation, pull requests merged in 2023-08, with the labels that each got.

#1025 Fixes bloodsucker moodlets
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_moodlets.dm
Labels: Fix, Modular

#1023 Finishes Helio's Science, Sci Maint + Moves AI Sat to Science
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit

#1030 Update clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
Labels: Fix, Modular

#1029 Infiltrators now have their own survival box
  fulp_modules/features/antagonists/infiltrators/infiltrator.dm
Labels: Fix, Modular

#1028 [Heliostation] Officers no longer have med access & fixes engineering external access
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix

#1031 Updates the cult stun
  fulp_modules/Z_edits/antag_edits/cult_stun.dm
Labels: Fix, Modular

#1033 AFK mentors are no longer hidden from MentorWho
  fulp_modules/features/mentors/mentorwho.dm
Labels: Quality of Life, Modular

#1035 The prison seating projector and portal board now appear on protolathes. Moves the latter to the sec protolathe.
  fulp_modules/features/prison/prison_kitchen/_restaurant.dm
Labels: Fix, Modular

#1036 Fixes medical storage door names on helio
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Stale
