Repository fulpstation/fulpstation, pull requests merged in 2023-09, with the labels that each got.

#1040 hopefully fixes bloodsuckers being given to new players
  fulp_modules/features/antagonists/rulesets/bloodsucker_rulesets.dm
Labels: Stale

#1039 Fixes Selene and Pubby ordnance freezer chamber
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Stale

#1048 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
Labels: Tools

#1046 add pixel offsets so the collision makes sense
  fulp_modules/mapping/station_objects/trees.dm
Labels: Fix, Modular

#1045 Frenzied torpor
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_sol.dm
Labels: Fix, Modular

#1049 Removes Bloodsucker objectives
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_nosferatu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_datum.dm
Labels: Removal, Modular

#1043 Removes the beefmen trauma preferences, lightly reworks the way Sleepless Dreamer works
  fulp_modules/_defines/species_defines.dm
  fulp_modules/features/species/beefmen/beefman_preferences.dm
  fulp_modules/features/species/beefmen/mob/beefman_organs.dm
  fulp_modules/features/species/beefmen/phobetor_trauma.dm
  fulp_modules/fulp_world/_global_vars.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/beefman_features.tsx
Labels: Balance, Modular
