Repository fulpstation/fulpstation, pull requests merged in 2023-06, with the labels that each got.

#991 Bloodsucker heart fixes, high pressure resistance, etc
  fulp_modules/_defines/bloodsuckers.dm
  fulp_modules/_defines/traits.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_sol.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_nosferatu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_coffin.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_objects.dm
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm
Labels: Fix, Merge Conflict, Modular, Code Improvement

#1002 Fix guides links
  README.md
Labels: Fix

#998 Pubby ordnance
  _maps/map_files/PubbyStation/PubbyStation.dmm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/beefman_features.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/antag_tips.tsx
Labels: Map Edit

#1003 reworks how monsters are hunted
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm
Labels: Balance, Modular

#1010 Fixes beefmen getting infinite burden
  fulp_modules/features/species/beefmen/mob/beefman.dm
Labels: Fix, Modular

#1001 few mh qol changes
  fulp_modules/features/antagonists/monster_hunter/hunting_contract.dm
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_datum.dm
  fulp_modules/features/antagonists/monster_hunter/white_rabbit.dm
Labels: Quality of Life, Modular

#1011 Fixes some BS runtimes
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/antagonists/rulesets/bloodsucker_rulesets.dm
Labels: Fix, Modular

#1012 Some map maintenance swag
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix
