Repository fulpstation/fulpstation, pull requests merged in 2023-04, with the labels that each got.

#940 Brings back the Bloodsucker roundend report
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
Labels: Fix, Modular

#939 Removes discord verification button
  fulp_modules/fulp_world/fulp_client.dm
  tgstation.dme
Labels: Removal, Modular

#938 fixes a runtime
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm
Labels: Fix, Modular

#941 Vassals HUDs now work with mesons
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/ex_vassal.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_datum.dm
Labels: Fix, Modular

#942 Fixes safety moth clothes
  fulp_modules/features/antagonists/ert/code/safety_moth.dm
Labels: Fix, Modular

#943 Fixes problems with beefmen tears
  fulp_modules/features/species/beefmen/phobetor_trauma.dm
Labels: Fix, Modular, Grammar/Spelling

#948 Removes the electrified grille/waste spawner in Heliostation engineering maintenace
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Balance

#952 Probably fixes being able to vassalize sec
  fulp_modules/_defines/bloodsuckers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
Labels: Fix, Modular

#951 https://github.com/fulpstation/fulpstation/pull/345 2
  fulp_modules/features/cargo/cargo.dm
  fulp_modules/features/toys/code/plushies.dm
  fulp_modules/features/toys/icons/toys.dmi
Labels: Feature, Fix, Quality of Life, Sprites, Balance, Modular

#936 Heliostation Emergency Shuttle
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/shuttles/emergency_helio.dmm
  fulp_modules/mapping/shuttles/map_templates.dm
Labels: Map Edit, Modular

#956 Fixes issues with helio station . dmm
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix

#944 Boring Bloodsucker Rebalance
  fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/haste.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/vassal_fold.dm
Labels: Balance, Modular

#776 Removes our TG edit from basemap
  _maps/_basemap.dm
  fulp_modules/mapping/_basemap.dm
  fulp_modules/tg_edits.md
  tgstation.dme
Labels: Modular, Code Improvement

#955 fixes BS report being all on one line
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
Labels: Fix, Modular

#958 replaces a set of codersprites with another set of codersprites
  fulp_modules/features/antagonists/infiltrators/infil_objectives.dm
  fulp_modules/features/antagonists/monster_hunter/icons/weapons.dmi
  fulp_modules/features/antagonists/monster_hunter/icons/weapons_lefthand.dmi
  fulp_modules/features/antagonists/monster_hunter/icons/weapons_righthand.dmi
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
Labels: Sprites, Modular

#946 feed minor change
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/icons/bs_leftinhand.dmi
  fulp_modules/features/antagonists/bloodsuckers/icons/bs_rightinhand.dmi
Labels: Balance, Modular

#945 redoes my selene pr
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix

#959 Adds an operating computer to Selene's morgue
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit

#963 Fixes and balances Bloodsuckers, adds admin testing support
  fulp_modules/_defines/bloodsuckers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_hud.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
Labels: Fix, Balance, Modular

#964 Removes the role preferences tg edit
  code/__DEFINES/role_preferences.dm
  fulp_modules/_defines/bloodsuckers.dm
  fulp_modules/fulp_world/fulp_world.dm
  fulp_modules/tg_edits.md
Labels: Modular, Code Improvement

#965 Removes our TG edit for roundend music
  code/__HELPERS/roundend.dm
  fulp_modules/sounds/code/credits.dm
  fulp_modules/tg_edits.md
Labels: Modular, Code Improvement

#966 Changes the beef tongue
  fulp_modules/features/species/beefmen/russian.dm
Labels: Modular, Code Improvement

#961 Heliostation Patch 3 - Bridge Rework; Medical Maint Revamp; Minor Fixes
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Feature, Map Edit, Fix

#962 adds the blood fountain to the wonderland for monsterhunters
  fulp_modules/features/antagonists/infiltrators/infil_items.dm
  fulp_modules/features/antagonists/monster_hunter/icons/blood_fountain.dmi
  fulp_modules/features/antagonists/monster_hunter/icons/weapons.dmi
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_abilities.dm
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
  fulp_modules/features/antagonists/monster_hunter/sounds/blood_vial_slurp.ogg
  fulp_modules/features/antagonists/monster_hunter/wonderland.dm
  fulp_modules/mapping/custom/wonderland.dmm
  tgstation.dme
Labels: Balance, Modular

#974 Removes some overlapping balloon alerts
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
Labels: Fix, Modular

#969 Fixes checks maybe
  fulp_modules/Z_edits/felinid_edit.dm
Labels: Fix, Modular

#970 Moves beefmen traumas to the brain, fixes suits
  code/modules/unit_tests/screenshots/screenshot_humanoids__datum_species_beefman.png
  fulp_modules/features/species/beefmen/mob/beefman.dm
  fulp_modules/features/species/beefmen/mob/beefman_organs.dm
  fulp_modules/features/species/icons/mob/clothing/beefclothing_worn.dmi
  tgstation.dme
Labels: Fix, Modular, Code Improvement
