Repository fulpstation/fulpstation, pull requests merged in 2023-11, with the labels that each got.

#1064 Adds Reload Mentors as an admin verb
  fulp_modules/Z_edits/fulp_verbs.dm
  fulp_modules/features/mentors/mentor.dm
  fulp_modules/features/mentors/mentor_clientprocs.dm
  tgstation.dme
Labels: Fix, Administration

#1065 Allows normal tongues to speak Space Russian
  fulp_modules/Z_edits/fulp_languages.dm
  fulp_modules/features/species/beefmen/russian.dm
  tgstation.dme
Labels: Fix, Modular

#1066 Re-adds the option to toggle antag tips
  fulp_modules/tg_edits.md
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/antag_tips.tsx
Labels: Fix

#1067 prison bot rebalance
  fulp_modules/features/prison/prison_kitchen/food_overwrites.dm
  fulp_modules/features/prison/prison_kitchen/prison_bots/head_of_security_bot.dm
  fulp_modules/features/prison/prison_kitchen/prison_bots/lizard_bot.dm
  fulp_modules/features/prison/prison_kitchen/prison_bots/prisoner_bot.dm
  fulp_modules/features/prison/prison_kitchen/prison_bots/rat_bot.dm
  fulp_modules/features/prison/prison_kitchen/prison_bots/warden_bot.dm
Labels: Fix, Balance, Modular

#1072 Code cleanup on halloween gifts and beacons
  fulp_modules/features/halloween/_code.dm
Labels: Fix, Modular, Code Improvement

#1074 Makes some minor additions to detective offices on helio and selene (NOTICE BOARDS :D)
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
Labels: Map Edit, Fix, Modular

#1070 Radios will no longer pick up tape recorders or holopads
  fulp_modules/Z_edits/fixes/radio.dm
  tgstation.dme
Labels: Fix, Modular

#1075 Fixes to pubbystation.com
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Map Edit, Fix, Balance

#1076 Fixes recycler direction on Helio
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit, Fix
