Repository fulpstation/fulpstation, pull requests merged in 2024-07, with the labels that each got.

#1227 Bloodsucker textual overhaul/grammar review
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_conversion.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_frenzy.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_life.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_moodlets.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/subsystem_sunlight.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_flavortext.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_malkavian.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_nosferatu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_vassal.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/cloak.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/feed.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/fortitude.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/masquerade.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/brawn.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/haste.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/lunge.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/trespass.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/auspex.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/dominate.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/tremere/thaumaturgy.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/distress.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/recuperate.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/vassal_fold.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/veil.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_coffin.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_objects.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/ex_vassal.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/vassal_procs.dm
Labels: Grammar/Spelling

#1224 Monster Hunter description changes
  fulp_modules/features/antagonists/monster_hunter/hunting_contract.dm
  fulp_modules/features/antagonists/monster_hunter/monsterhunter_weapons.dm
  fulp_modules/features/antagonists/monster_hunter/wonderland.dm
Labels: Feature, Fix, Grammar/Spelling

#1229 Minor edits to Theia Station's center
  _maps/map_files/TheiaStation/TheiaStation.dmm
Labels: Map Edit, Modular

#1233 Fixes nanites breaking IDs
  fulp_modules/features/nanites/code/nanite_component.dm
Labels: Fix, Modular
