Repository fulpstation/fulpstation, pull requests merged in 2024-04, with the labels that each got.

#1186 Minor helio fix and qol
  _maps/map_files/Heliostation/Heliostation.dmm
Labels: Map Edit

#1189 Changes to blood chair and fixes dirtying
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_datum.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_objectives.dm
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/bloodsucker_sol.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/gohome.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_coffin.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
Labels: Stale

#1190 general nice stuff for mentors
  fulp_modules/_defines/mentors.dm
  fulp_modules/features/mentors/mentor.dm
  fulp_modules/features/mentors/mentor_clientprocs.dm
  fulp_modules/features/mentors/mentor_manager.dm
  fulp_modules/features/mentors/mentor_state.dm
  fulp_modules/features/mentors/mentorhelp.dm
  fulp_modules/features/mentors/mentorpm.dm
  fulp_modules/features/mentors/mentorsay.dm
  fulp_modules/features/mentors/mentorwho.dm
  tgstation.dme
  tgui/packages/fulpui-patches/RequestManagerFulp.jsx
Labels: Code Improvement

#1196 Vassal fold ensures you're a revenge vassal
  fulp_modules/features/antagonists/bloodsuckers/code/powers/_powers.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/vassal_fold.dm
Labels: Fix

#1192 Fulp code improvements
  code/game/area/areas/shuttles.dm
  fulp_modules/features/clothing/neck/beefman_locket.dm
  fulp_modules/features/toys/code/plushies.dm
  fulp_modules/fulp_world/_global_vars.dm
  fulp_modules/mapping/areas/areas.dm
  fulp_modules/mapping/ruins/space/beefman_station/beefman_station.dm
  fulp_modules/mapping/station_objects/decals.dm
  fulp_modules/sounds/ambience/beef_station.ogg
  fulp_modules/sounds/ambience/spacepad.ogg
  fulp_modules/sounds/arrival/ApproachingFulp.ogg
  fulp_modules/sounds/code/ambience.dm
  fulp_modules/sounds/credits/Fulp_Piano.ogg
  fulp_modules/sounds/credits/Fulp_Piano_Old.ogg
  fulp_modules/sounds/credits/shuttlesent.ogg
  fulp_modules/sounds/effects/batong.ogg
  fulp_modules/sounds/effects/jumpscare.ogg
  fulp_modules/sounds/effects/kero.ogg
  fulp_modules/sounds/effects/pico.ogg
  fulp_modules/sounds/roundend/i_got_banned_on_fulpstation.ogg
  fulp_modules/sounds/roundend/imaghoul.ogg
Labels: Code Improvement

#1197 Healing nanites works better on Lavaland
  fulp_modules/Z_edits/hud_edits.dm
  fulp_modules/features/nanites/code/nanite_component.dm
  fulp_modules/features/nanites/code/nanite_hud.dm
  fulp_modules/features/nanites/code/programs/healing.dm
  fulp_modules/features/nanites/code/programs/utility.dm
Labels: Stale, Feature, Balance

#1107 Adds Theia (formerly Fulpstation) Station
  _maps/map_files/TheiaStation/TheiaStation.dmm
  _maps/shuttles/arrival_fulp.dmm
  _maps/shuttles/cargo_fulp.dmm
  _maps/theiastation.json
  config/maps.txt
  fulp_modules/mapping/areas/areas.dm
  fulp_modules/mapping/icons/mapping.dmi
  fulp_modules/mapping/shuttles/map_templates.dm
  fulp_modules/mapping/station_objects/decals.dm
  fulp_modules/mapping/station_objects/signs.dm
Labels: map
