Repository fulpstation/fulpstation, pull requests merged in 2024-02, with the labels that each got.

#1095 Bloodsucker sol is now by the minute
  fulp_modules/features/antagonists/bloodsuckers/code/bloodsucker/subsystem_sunlight.dm
Labels: Balance, Modular

#1097 Fixes vassals keeping abilities post-BS death
  fulp_modules/features/antagonists/bloodsuckers/code/clans/_clan.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_malkavian.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_nosferatu.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_tremere.dm
  fulp_modules/features/antagonists/bloodsuckers/code/clans/clan_ventrue.dm
  fulp_modules/features/antagonists/bloodsuckers/code/vassal/types/favorite_vassal.dm
Labels: Fix, Modular

#1098 Removes cult leader antag tips
  fulp_modules/features/antagonists/antag_tips/antag_tip_integration.dm
Labels: Fix, Modular

#1099 recuperate works while in crit & fixes mesmerize
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/mesmerize.dm
  fulp_modules/features/antagonists/bloodsuckers/code/powers/vassal/recuperate.dm
Labels: Fix, Balance, Modular

#1101 removes some copy paste from mentor stuff
  fulp_modules/features/mentors/mentor.dm
  fulp_modules/features/mentors/mentor_clientprocs.dm
  fulp_modules/features/mentors/mentorpm.dm
  fulp_modules/features/mentors/mentorsay.dm
Labels: Modular, Code Improvement

#1102 brawn takes armor into account
  fulp_modules/features/antagonists/bloodsuckers/code/powers/targeted/brawn.dm
  fulp_modules/features/antagonists/bloodsuckers/code/structures/bloodsucker_crypt.dm
Labels: Balance, Modular

#1109 Shrimp plushie
  _maps/map_files/Heliostation/Heliostation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/SeleneStation/SeleneStation.dmm
  fulp_modules/features/cargo/cargo.dm
  fulp_modules/features/toys/code/plushies.dm
  fulp_modules/features/toys/code/shrimp_plush.dm
  fulp_modules/features/toys/icons/toys.dmi
  fulp_modules/sounds/sound/effects/kero.ogg
  tgstation.dme
Labels: Feature, Modular

#1103 Automatic TGS DMAPI Update
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v5/__interop_version.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/bridge.dm
  code/modules/tgs/v5/topic.dm
  code/modules/tgs/v5/undefs.dm
Labels: Stale, Tools

#1114 Fixes description for temperature adjustment
  fulp_modules/features/nanites/code/programs/healing.dm
Labels: Stale
